In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

sns.set_theme(style="whitegrid")
plt.rcParams['figure.figsize'] = (12,6)

print("Libraries loaded successfully")

Libraries loaded successfully

In [2]:
#load data of all five years

df_2015 = pd.read_csv("csv/2015.csv")
df_2016 = pd.read_csv("csv/2016.csv")
df_2017 = pd.read_csv("csv/2017.csv")
df_2018 = pd.read_csv("csv/2018.csv")
df_2019 = pd.read_csv("csv/2019.csv")

print(df_2015.shape)
print(df_2016.shape)
print(df_2017.shape)
print(df_2018.shape)
print(df_2019.shape)

print("2015 columns:", df_2015.columns.tolist())
print("2016 columns:", df_2016.columns.tolist())
print("2017 columns:", df_2017.columns.tolist())
print("2018 columns:", df_2018.columns.tolist())
print("2019 columns:", df_2019.columns.tolist())

(158, 12)
(157, 13)
(155, 12)
(156, 9)
(156, 9)
2015 columns: ['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Standard Error', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']
2016 columns: ['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Lower Confidence Interval', 'Upper Confidence Interval', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity', 'Dystopia Residual']
2017 columns: ['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high', 'Whisker.low', 'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.', 'Freedom', 'Generosity', 'Trust..Government.Corruption.', 'Dystopia.Residual']
2018 columns: ['Overall rank', 'Country or region', 'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']
2019 columns: ['Overall rank', 'Country or region', 'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Generosity', 'Perceptions of corruption']

In [3]:
#standardize all dataframes to have same column names

#2015
df_2015 = df_2015[['Country', 'Region', 'Happiness Rank', 'Happiness Score',
                    'Economy (GDP per Capita)', 'Health (Life Expectancy)',
                    'Freedom', 'Generosity', 'Trust (Government Corruption)']]
df_2015.columns = ['Country', 'Region', 'Rank', 'Score', 'GDP', 'Health', 'Freedom', 'Generosity', 'Corruption']
df_2015['Year'] = 2015

# 2016
df_2016 = df_2016[['Country', 'Region', 'Happiness Rank', 'Happiness Score',
                    'Economy (GDP per Capita)', 'Health (Life Expectancy)',
                    'Freedom', 'Generosity', 'Trust (Government Corruption)']]
df_2016.columns = ['Country', 'Region', 'Rank', 'Score', 'GDP', 'Health', 'Freedom', 'Generosity', 'Corruption']
df_2016['Year'] = 2016

# 2017 (dots in column names)
df_2017 = df_2017[['Country', 'Happiness.Rank', 'Happiness.Score',
                    'Economy..GDP.per.Capita.', 'Health..Life.Expectancy.',
                    'Freedom', 'Generosity', 'Trust..Government.Corruption.']]
df_2017.columns = ['Country', 'Rank', 'Score', 'GDP', 'Health', 'Freedom', 'Generosity', 'Corruption']
df_2017['Year'] = 2017

# 2018
df_2018 = df_2018[['Country or region', 'Overall rank', 'Score', 'GDP per capita',
                    'Healthy life expectancy', 'Freedom to make life choices',
                    'Generosity', 'Perceptions of corruption']]
df_2018.columns = ['Country', 'Rank', 'Score', 'GDP', 'Health', 'Freedom', 'Generosity', 'Corruption']
df_2018['Year'] = 2018

# 2019
df_2019 = df_2019[['Country or region', 'Overall rank', 'Score', 'GDP per capita',
                    'Healthy life expectancy', 'Freedom to make life choices',
                    'Generosity', 'Perceptions of corruption']]
df_2019.columns = ['Country', 'Rank', 'Score', 'GDP', 'Health', 'Freedom', 'Generosity', 'Corruption']
df_2019['Year'] = 2019

print("Cleaning done!")

Cleaning done!

In [4]:
#merge all the years in one dataframe
df = pd.concat([df_2015, df_2016, df_2017, df_2018, df_2019], ignore_index=True)

print("Shape:", df.shape)
print("\nFirst 5 rows:")
df.head()

Shape: (782, 10)

First 5 rows:

,Country,Region,Rank,Score,GDP,Health,Freedom,Generosity,Corruption,Year
0,Switzerland,Western Europe,1,7.587,1.39651,0.94143,0.66557,0.29678,0.41978,2015
1,Iceland,Western Europe,2,7.561,1.30232,0.94784,0.62877,0.43630,0.14145,2015
2,Denmark,Western Europe,3,7.527,1.32548,0.87464,0.64938,0.34139,0.48357,2015
3,Norway,Western Europe,4,7.522,1.45900,0.88521,0.66973,0.34699,0.36503,2015
4,Canada,North America,5,7.427,1.32629,0.90563,0.63297,0.45811,0.32957,2015

In [5]:
# Check missing values and data types
print("Missing values:\n", df.isnull().sum())
print("\nData types:\n", df.dtypes)

Missing values:
 Country         0
Region        467
Rank            0
Score           0
GDP             0
Health          0
Freedom         0
Generosity      0
Corruption      1
Year            0
dtype: int64

Data types:
 Country           str
Region            str
Rank            int64
Score         float64
GDP           float64
Health        float64
Freedom       float64
Generosity    float64
Corruption    float64
Year            int64
dtype: object

In [6]:
print(df_2015["Country"])


# region_map = df_2015.set_index('Country')['Region'].to_dict()
# print(region_map)

0      Switzerland
1          Iceland
2          Denmark
3           Norway
4           Canada
          ...
153         Rwanda
154          Benin
155          Syria
156        Burundi
157           Togo
Name: Country, Length: 158, dtype: str

In [7]:
# Fix 1: Fill missing Region
region_map = df_2015.set_index('Country')['Region'].to_dict()
df['Region'] = df['Region'].fillna(df['Country'].map(region_map))

# Fix 2: Fill missing Corruption with median
df['Corruption'] = df['Corruption'].fillna(df['Corruption'].median())

print("Missing values after fix:\n", df.isnull().sum())

Missing values after fix:
 Country        0
Region        19
Rank           0
Score          0
GDP            0
Health         0
Freedom        0
Generosity     0
Corruption     0
Year           0
dtype: int64

In [8]:
#final look at clean data
print("shape:", df.shape)
print("\n Years in data: ", df['Year'].unique())
print("\nSample countries:", df['Country'].unique()[:10])
print("\nRegions:", df['Region'].unique())
df.describe()

shape: (782, 10)

 Years in data:  [2015 2016 2017 2018 2019]

Sample countries: <StringArray>
['Switzerland',     'Iceland',     'Denmark',      'Norway',      'Canada',
     'Finland', 'Netherlands',      'Sweden', 'New Zealand',   'Australia']
Length: 10, dtype: str

Regions: <StringArray>
[                 'Western Europe',                   'North America',
       'Australia and New Zealand', 'Middle East and Northern Africa',
     'Latin America and Caribbean',               'Southeastern Asia',
      'Central and Eastern Europe',                    'Eastern Asia',
              'Sub-Saharan Africa',                   'Southern Asia',
                               nan]
Length: 11, dtype: str

,Rank,Score,GDP,Health,Freedom,Generosity,Corruption,Year
count,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000,782.000000
mean,78.698210,5.379018,0.916047,0.612416,0.411091,0.218576,0.125392,2016.993606
std,45.182384,1.127456,0.407340,0.248309,0.152880,0.122321,0.105756,1.417364
min,1.000000,2.693000,0.000000,0.000000,0.000000,0.000000,0.000000,2015.000000
25%,40.000000,4.509750,0.606500,0.440183,0.309768,0.130000,0.054250,2016.000000
50%,79.000000,5.322000,0.982205,0.647310,0.431000,0.201982,0.091000,2017.000000
75%,118.000000,6.189500,1.236187,0.808000,0.531000,0.278832,0.155861,2018.000000
max,158.000000,7.769000,2.096000,1.141000,0.724000,0.838075,0.551910,2019.000000